FROM node:22

RUN mkdir /data && echo "docker-i-know-best" > /data/password.txt

# docker buildx build --platform linux/arm64,linux/amd64 -f Dockerfile.base -t omribarzik/docker-workshop:node --push .